### ISSUE TITLE
http://www.heiho.net/pconsole/ gives "404 Not Found"

### ISSUE THREAD

**Issue by xtaran** [walterdejong/pconsole#6]
The link http://www.heiho.net/pconsole/ as present in the descirption of this repository as well as in the README seems to more exist.

Please either reinstantiate the previous web page at the above mentioned URL or change the mentioned links to the current location of the pconsole homepage.

**Comment by walterdejong** [comment]
Thanks for reporting this. The new URL is
https://walterdejong.github.io/pconsole
